-- ============================================================================
-- Endpoint: POST /api/v1/contacts/
-- API Version: v1
-- Description: Create a new contact record using the ContactCreate schema.
--              All fields are optional. UUID is auto-generated if not provided.
-- ============================================================================
--
-- Parameters:
--   Body Parameters (all optional):
--     uuid (text, optional) - Contact UUID. If not provided, one will be generated using uuid_generate_v4()
--     first_name (text, optional) - Contact's first name
--     last_name (text, optional) - Contact's last name
--     company_id (text, optional) - UUID of the related company
--     email (text, optional) - Contact's email address
--     title (text, optional) - Contact's job title
--     departments (text[], optional) - Array of department names
--     mobile_phone (text, optional) - Contact's mobile phone number
--     email_status (text, optional) - Email verification status
--     text_search (text, optional) - Free-form search text, e.g., location information
--     seniority (text, optional) - Contact's seniority level (defaults to '_' if not provided)
--
-- Response Structure:
--   Returns ContactDetail with all contact fields including generated UUID and timestamps.
--
-- Response Codes:
--   201 Created: Contact created successfully
--   400 Bad Request: Invalid request data
--   401 Unauthorized: Authentication required
--   403 Forbidden: Admin access and X-Contacts-Write-Key header required
--   500 Internal Server Error: Error occurred while creating contact
--
-- Authentication:
--   Required - Bearer token (admin) and X-Contacts-Write-Key header
--
-- Example Usage:
--   POST /api/v1/contacts/
--   Content-Type: application/json
--   Authorization: Bearer <admin_token>
--   X-Contacts-Write-Key: <write_key>
--   
--   {
--     "first_name": "John",
--     "last_name": "Doe",
--     "email": "john.doe@example.com",
--     "title": "Software Engineer"
--   }
-- ============================================================================

-- Query: Insert new contact (PostgreSQL)
-- Note: The ORM uses SQLAlchemy which handles parameter binding. This shows the equivalent SQL.
--       UUID and seniority defaults are handled by service layer before insert.
INSERT INTO contacts (
    uuid,
    first_name,
    last_name,
    company_id,
    email,
    title,
    departments,
    mobile_phone,
    email_status,
    text_search,
    seniority,
    created_at,
    updated_at
)
VALUES (
    $1,  -- uuid (generated by service layer if not provided)
    $2,  -- first_name
    $3,  -- last_name
    $4,  -- company_id
    $5,  -- email
    $6,  -- title
    $7,  -- departments (array)
    $8,  -- mobile_phone
    $9,  -- email_status
    $10, -- text_search
    $11, -- seniority (defaults to '_' if not provided, set by service layer)
    $12, -- created_at (set by service layer to current timestamp)
    $13  -- updated_at (set by service layer to current timestamp)
)
RETURNING 
    id,
    uuid,
    first_name,
    last_name,
    company_id,
    email,
    title,
    departments,
    mobile_phone,
    email_status,
    text_search,
    seniority,
    created_at,
    updated_at;

-- Query: SQLite special handling for ID generation
-- Note: SQLite doesn't support auto-increment properly, so ORM manually calculates next ID
--       This happens BEFORE the INSERT in the Python code
-- Step 1: Get max ID
SELECT MAX(id) FROM contacts;

-- Step 2: Insert with manually calculated ID (next_id = max_id + 1)
-- The ORM sets contact.id = next_id before session.add()
-- Then SQLAlchemy uses the provided ID value in the INSERT

