-- ============================================================================
-- Endpoint: POST /api/v2/apollo/analyze
-- API Version: v2
-- Description: Analyze an Apollo.io URL and return structured parameter breakdown. This endpoint parses Apollo.io search URLs (typically from the People Search page) and extracts all query parameters, categorizing them into logical groups.
-- ============================================================================
--
-- Request Body Parameters:
--   $1: url (text, required) - Apollo.io URL to analyze (must be from apollo.io domain)
--
-- Response Structure:
-- {
--   "url": "https://app.apollo.io/#/people?...",
--   "url_structure": {
--     "base_url": "https://app.apollo.io",
--     "hash_path": "/people",
--     "query_string": "...",
--     "has_query_params": true
--   },
--   "categories": [
--     {
--       "name": "Pagination",
--       "parameters": [...],
--       "total_parameters": 1
--     },
--     ...
--   ],
--   "statistics": {
--     "total_parameters": 7,
--     "total_parameter_values": 7,
--     "categories_used": 5,
--     "categories": [...]
--   },
--   "raw_parameters": {...}
-- }
--
-- Response Codes:
--   200 OK: URL analyzed successfully
--   400 Bad Request: Invalid URL, not from Apollo.io domain, or missing URL field
--   401 Unauthorized: Authentication required
--   500 Internal Server Error: Error occurred while analyzing the URL
--
-- Note: This endpoint does not perform any database queries. It only parses and analyzes
-- the Apollo.io URL structure. The analysis is performed in the application layer using
-- the ApolloAnalysisService. Industry Tag IDs are automatically converted to readable
-- industry names in the API response.
--
-- Example Usage:
--   POST /api/v2/apollo/analyze
--   Content-Type: application/json
--   Authorization: Bearer <access_token>
--   
--   {
--     "url": "https://app.apollo.io/#/people?contactEmailStatusV2[]=verified&personLocations[]=california&personTitles[]=CEO&organizationNumEmployeesRanges[]=11,50&page=1&sortByField=recommendations_score&sortAscending=false"
--   }
-- ============================================================================

-- Note: This endpoint does not execute SQL queries.
-- The URL analysis is performed entirely in the application layer.
-- The ApolloAnalysisService parses the URL, extracts query parameters,
-- categorizes them, and converts industry tag IDs to readable names.
--
-- The response structure includes:
-- - URL structure breakdown (base URL, hash path, query string)
-- - Categorized parameters with descriptions
-- - Parameter values (URL-decoded)
-- - Statistics about the search criteria
-- - Raw parameters dictionary

-- No SQL query required - URL parsing and analysis handled in application layer

