-- ============================================================================
-- Endpoint: POST /api/v2/linkedin/export
-- API Version: v2
-- Description: Export contacts and companies by multiple LinkedIn URLs. Accepts a list of LinkedIn URLs, searches for matching contacts and companies, and generates a combined CSV file containing all matches plus unmatched URLs marked as "not_found". The export is processed asynchronously via a background Celery job.
-- ============================================================================
--
-- Request Body Parameters:
--   urls (array[string], required, min: 1) - List of LinkedIn URLs to search and export. Can be person LinkedIn URLs or company LinkedIn URLs.
--
-- Response Structure:
--   Returns LinkedInExportResponse containing:
--   - export_id: UUID of the export record
--   - download_url: Signed URL for downloading the CSV file (initially empty, updated when export completes)
--   - expires_at: Timestamp when the download URL expires (24 hours from creation)
--   - contact_count: Number of contacts included in the export (initially 0, updated when export completes)
--   - company_count: Number of companies included in the export (initially 0, updated when export completes)
--   - status: Export status (pending, processing, completed, failed, cancelled)
--   - job_id: Celery task ID for tracking the background job
--
-- Response Codes:
--   201 Created: Export job created successfully
--   400 Bad Request: At least one LinkedIn URL is required, or all URLs are empty/invalid
--   401 Unauthorized: Authentication required
--   500 Internal Server Error: Error occurred during export creation
--
-- Authentication:
--   Required - Bearer token in Authorization header
--
-- Example Usage:
--   POST /api/v2/linkedin/export
--   Content-Type: application/json
--   Authorization: Bearer <access_token>
--   
--   {
--     "urls": [
--       "https://www.linkedin.com/in/john-doe",
--       "https://www.linkedin.com/company/tech-corp",
--       "https://www.linkedin.com/in/jane-smith"
--     ]
--   }
-- ============================================================================

-- ORM Implementation Notes:
--   The LinkedIn export endpoint uses the following workflow:
--   
--   ENDPOINT HANDLER (app/api/v2/endpoints/linkedin.py):
--   1. Validates request: checks that at least one valid URL is provided
--   2. Creates export record in user_exports table with status="pending"
--      - Stores linkedin_urls in user_exports.linkedin_urls column for reference
--      - This allows users to see what URLs they originally requested
--   3. Queues background Celery task: process_linkedin_export.delay(export_id, urls)
--   4. Returns LinkedInExportResponse with export_id and job_id
--   
--   BACKGROUND TASK (app/tasks/export_tasks.py):
--   1. Updates export status to "processing"
--   2. Calls LinkedInService.search_by_multiple_urls() to search all URLs in parallel
--   3. Collects unique contact_uuids, company_uuids, and unmatched_urls
--   4. Calls ExportService.generate_linkedin_export_csv() to generate CSV
--   5. Updates export status to "completed" and generates signed download URL
--   
--   LINKEDIN SERVICE (app/services/linkedin_service.py):
--   - search_by_multiple_urls() method:
--     1. Normalizes and validates all URLs
--     2. Searches each URL in parallel using asyncio.gather()
--     3. For each URL, calls search_by_url() which:
--        - Searches ContactMetadata by linkedin_url (parallel with company search)
--        - Searches CompanyMetadata by linkedin_url (parallel with contact search)
--        - Uses optimized sequential queries with batch fetching
--        - Returns LinkedInSearchResponse with contacts and companies
--     4. Collects all unique contact UUIDs from ContactWithRelations
--     5. Collects all unique company UUIDs from CompanyWithRelations
--     6. Tracks URLs that didn't match any contacts or companies
--     7. Returns tuple: (contact_uuids, company_uuids, unmatched_urls)
--   
--   EXPORT SERVICE (app/services/export_service.py):
--   - generate_linkedin_export_csv() method:
--     1. Creates CSV with combined structure including:
--        - record_type column: "contact", "company", or "not_found"
--        - linkedin_url column: LinkedIn URL for reference
--        - All contact fields (populated for contact rows)
--        - All contact metadata fields (populated for contact rows)
--        - All company fields (populated for company rows and related companies)
--        - All company metadata fields (populated for company rows and related companies)
--     2. Writes contact rows: fetches each contact with relations and writes full data
--     3. Writes company rows: fetches each company with metadata and writes full data
--     4. Writes not_found rows: only record_type and linkedin_url populated
--     5. Uploads CSV to S3 (if configured) or saves locally
--     6. Returns file path (S3 key or local path)
--   
--   OPTIMIZATIONS IMPLEMENTED:
--   1. Parallel URL Searching: All LinkedIn URLs searched simultaneously using asyncio.gather()
--   2. Parallel Contact/Company Search: Within each URL search, contact and company searches run in parallel
--   3. UUID Deduplication: Automatic deduplication of contact and company UUIDs
--   4. Batch Processing: Large result sets handled efficiently with batching
--   5. Background Processing: Export generation doesn't block the API request
--   6. Progress Tracking: Export progress tracked in database for monitoring
--   7. Error Handling: Failed URLs logged but don't stop the entire export
--   
--   CSV STRUCTURE:
--   The generated CSV includes a record_type column with three possible values:
--   - "contact": Row represents a contact found from the LinkedIn URLs
--   - "company": Row represents a company found from the LinkedIn URLs
--   - "not_found": Row represents a LinkedIn URL that didn't match any contacts or companies
--   
--   For contact rows: All contact and contact metadata fields populated, plus related company data
--   For company rows: All company and company metadata fields populated, contact fields empty
--   For not_found rows: Only record_type and linkedin_url populated, all other fields empty
--   
--   DATABASE TABLES USED:
--   - user_exports: Stores export job records with status, file paths, and metadata
--     * linkedin_urls column: Stores original LinkedIn URLs used for the export (text[])
--     * Only populated for exports created via POST /api/v2/linkedin/export
--   - contacts: Contact records fetched by UUID
--   - contacts_metadata: Contact metadata records with linkedin_url
--   - companies: Company records fetched by UUID
--   - companies_metadata: Company metadata records with linkedin_url
--   
--   RELATED ENDPOINTS:
--   - GET /api/v2/exports/{export_id}/status: Check export progress and status
--   - GET /api/v2/exports/{export_id}/download: Download the generated CSV file
--   - GET /api/v2/exports/: List all exports for the current user
--   
--   PERFORMANCE CONSIDERATIONS:
--   - Large URL lists (100+) may take longer to process
--   - Export generation time depends on number of contacts/companies found
--   - CSV file size depends on number of records and fields populated
--   - S3 upload (if configured) adds network latency but enables scalable storage
--   - Local file storage suitable for smaller exports or development environments
--   
--   SECURITY:
--   - All exports are user-scoped (only accessible by the creating user)
--   - Signed download URLs expire after 24 hours
--   - Download URLs require valid signed token for access
--   - Export records include user_id for authorization checks
--   
--   ERROR HANDLING:
--   - Invalid URLs are filtered out before processing
--   - Failed URL searches are logged but don't stop the export
--   - Missing contacts/companies are skipped with warning logs
--   - Export failures update status to "failed" with error message
--   - Background task errors are logged and tracked in export record
-- ============================================================================

