-- ============================================================================
-- Endpoint: DELETE /api/v2/exports/files
-- API Version: v2
-- Description: Delete all CSV export files from the filesystem. Admin-only endpoint. This permanently deletes all CSV files associated with exports, but does not delete the export records from the database. Use with caution.
-- ============================================================================
--
-- Parameters:
--   $1: user_id (text, required) - User ID from authenticated session (must be admin)
--
-- Response Codes:
--   200 OK: Files deleted successfully
--   401 Unauthorized: Authentication required
--   403 Forbidden: Admin access required
--   500 Internal Server Error: Error occurred while deleting files
--
-- Response Structure:
-- {
--   "message": "All CSV export files deleted successfully",
--   "deleted_count": 42
-- }
--
-- Note: This endpoint deletes CSV files from the filesystem but does not delete
-- export records from the user_exports table. The file_path and file_name fields
-- in the database are not updated by this operation.
-- File deletion is performed in the application layer using the file system.
-- This is an admin-only operation for maintenance purposes.
--
-- Example Usage:
--   DELETE /api/v2/exports/files
--   Authorization: Bearer <admin_access_token>
-- ============================================================================

-- Note: This endpoint does not execute SQL queries.
-- File deletion is performed entirely in the application layer using the file system.
-- The endpoint:
-- 1. Verifies the user is an admin
-- 2. Scans the exports directory for CSV files
-- 3. Deletes all CSV files found
-- 4. Returns a count of deleted files
--
-- The user_exports table records are not modified by this operation.
-- Export records remain in the database for audit purposes.

-- No SQL query required - file deletion handled in application layer

